#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 10000
#logging:
#  level:
#    com.liulin: debug
