spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: test_route_qq
        uri: https://www.qq.com
        predicates:
        - Query=url,qq

      - id: admin_route
        uri: lb://gulimall-product
        predicates:
          - Path=/api/product/**
        filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

      - id: admin_route
        uri: lb://renren-fast
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


#  application:
#    name: gulimall-gateway
server:
  port: 88


