spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route_qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
#  application:
#    name: gulimall-gateway
server:
  port: 88


